from prometheus_client import Counter, Histogram, Gauge

# ── Request-level metrics ─────────────────────────────────
REQUEST_COUNT = Counter(
    "llm_requests_total",
    "Total number of requests",
    ["method", "endpoint", "status_code"]
)

REQUEST_LATENCY = Histogram(
    "llm_request_latency_seconds",
    "Request latency in seconds",
    ["endpoint"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
)

ACTIVE_REQUESTS = Gauge(
    "llm_active_requests",
    "Number of requests currently being processed"
)

QUEUE_DEPTH = Gauge(
    "llm_queue_depth",
    "Pending jobs in the Redis request queue"
)

WORKER_COUNT = Gauge(
    "llm_worker_count",
    "Number of workers currently registered with the load balancer"
)

# ── Worker-level metrics ──────────────────────────────────
WORKER_ACTIVE_REQUESTS = Gauge(
    "llm_worker_active_requests",
    "Active requests per worker",
    ["worker_url"]
)

WORKER_REQUEST_COUNT = Counter(
    "llm_worker_requests_total",
    "Total requests per worker",
    ["worker_url", "status"]
)

WORKER_LATENCY = Histogram(
    "llm_worker_latency_seconds",
    "Per-worker response latency",
    ["worker_url"],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0]
)

WORKER_HEALTH = Gauge(
    "llm_worker_healthy",
    "Worker health status (1=healthy, 0=unhealthy)",
    ["worker_url"]
)

# ── Agent/workflow/context metrics (Phase 13, REDESIGN.md §47-49) ─
# `fleet_` prefix (vs. the `llm_` metrics above) marks the new
# agent-aware layer added by the redesign — the older metrics aren't
# renamed, to avoid breaking the existing dashboard's queries.
#
# Deliberately NOT labeled by agent_id/workflow_id: those are arbitrary,
# unbounded strings (every simulated/real workflow gets a fresh uuid),
# and an unbounded-cardinality Prometheus label is a well-known way to
# take down a metrics backend. Per-agent/per-workflow detail is available
# via the structured `[Fleet] event=received ...` logs instead; these
# metrics are fleet-wide aggregates.
#
# Also deliberately NOT included: fleet_context_tokens_before/after/saved,
# fleet_context_selection_seconds, fleet_context_compression_seconds,
# fleet_memory_retrieval_seconds, fleet_memory_hits/misses. Those map to
# context/selection.py, context/compression.py, and memory/retrieval.py —
# none of which any live route calls yet (confirmed by a brutal live
# audit; see docs/migration-plan.md). Adding metrics for code nothing
# invokes would just be permanently-zero dead series, which is worse than
# no metric at all — it looks like a live signal and isn't one.

AGENT_REQUEST_COUNT = Counter(
    "fleet_agent_requests_total",
    "Requests through the agent-aware endpoints, tagged by whether agent_id was supplied",
    ["endpoint", "has_agent_id"]
)

AGENT_WORKFLOW_FAILURES = Counter(
    "fleet_agent_workflow_failures_total",
    "Agent-aware requests (workflow_id present) that failed",
    ["endpoint"]
)

CONTEXT_TOKENS = Histogram(
    "fleet_context_tokens",
    "Context tokens per agent-aware request, measured at routing time (REDESIGN.md §24/§41)",
    buckets=[128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768]
)

CONTEXT_ITEMS_RECORDED = Counter(
    "fleet_context_items_recorded_total",
    "ContextItems actually persisted into context_manager"
)

CONTEXT_CAPACITY_REJECTIONS = Counter(
    "fleet_context_capacity_rejections_total",
    "Requests rejected because no worker had enough context capacity"
)

INPUT_TOKENS_TOTAL = Counter(
    "fleet_input_tokens_total",
    "Prompt tokens sent to workers (Ollama's prompt_eval_count)",
    ["worker_url"]
)

OUTPUT_TOKENS_TOTAL = Counter(
    "fleet_output_tokens_total",
    "Completion tokens generated by workers (Ollama's eval_count)",
    ["worker_url"]
)